// Dependency-free static renderer. All public pages work without JavaScript.
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const publicDir = fileURLToPath(new URL('../public/', import.meta.url));
const email = 'ali.ozkul@icloud.com';
// Enable only after the App Store listing is publicly available.
const appStoreAvailable = false;
const appStoreURL = 'https://apps.apple.com/app/id6810970852';
const githubPrivacy = 'https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement';
const githubPages = 'https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages';
const applePrivacy = 'https://www.apple.com/legal/privacy/';
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const mail = `<a href="mailto:${email}">${email}</a>`;

const copy = {
  tr: {
    name: 'Türkçe', skip: 'İçeriğe geç', nav: ['Uygulamayı keşfet', 'Destek', 'Gizlilik'], language: 'Dil seçimi',
    title: 'UFFF — Sesine bir başrol ver.', description: 'Sesini kendi küçük çizgi filmine dönüştür. Karakterini, sahneni ve animasyonunu seç; kaydet ve paylaş. iPhone için UFFF.',
    eyebrow: 'Küçük bir ses. Büyük bir karakter.', heading: 'İçinden<br>geldiği gibi.<br><em>Ufff’la.</em>',
    lead: 'Bir iç çekiş, komik bir cümle, minicik bir dilek. Sesine bir başrol ver; kendi küçük çizgi filmini yap.',
    cta: 'Nasıl çalışır?', status: 'Yakında App Store’da', download: 'App Store’da görüntüle', meta: 'iPhone · iOS 18+', free: 'İlk 3 yaratık ücretsiz',
    art: 'Başrolün hazır.', filmAlt: 'UFFF önizlemesinde doğum günü pastalarıyla duran sarı Dilek Tutucu karakteri.', charactersAlt: 'UFFF uygulamasındaki renkli karakter seçim ekranı.',
    how: ['Sahne senin', 'Dört seçim.<br>Bir sürü küçük drama.', 'Karakter → Sahne → Animasyon → Ses kaydı. Sonra? Önizle, gülümse, paylaş.'],
    steps: [
      ['Karakterini seç.', '18 farklı karakterden biri sesinin yeni yüzü olsun.'],
      ['Sahneyi kur.', '14 sahne arasından küçük filminin dünyasını seç.'],
      ['Harekete geçir.', '18 animasyondan biriyle hikâyeye biraz hareket kat.'],
      ['Sesini bırak.', '5–8 saniyelik bir kayıt öneririz. Son dokunuş önizlemede.']
    ],
    character: ['Biraz tuhaf. Çok sen.', 'Her sesin<br>bir karakteri var.', 'Utangaç bir merhaba, kocaman bir ufff, fazlasıyla dramatik bir gün. İstediğin karakteri seç; kaydının ritmiyle canlansın.', ['18 karakter', 'Doğal, ince ve kalın ses', 'Yerel ikili sahne']],
    occasions: ['Bir bahaneye gerek yok', 'Ama kutlanacak<br>bir şey varsa…', 'Bir “seni seviyorum”u, doğum günü dileğini ya da sıradan bir salı gününü küçük bir gösteriye çevir.', ['Aşk', 'Sevgililer Günü', 'Doğum günü', 'Yıl dönümü', 'Kutlama', 'Sadece canın istedi']],
    share: ['Küçük film. Büyük gülümseme.', 'Önizle. Sakla. Gönder.', 'Animasyonunu sesli MP4 video ya da PNG kart olarak dışa aktar. Oluşturdukların kütüphanende kalsın; istediğin zaman yeniden aç.', 'MP4 video · PNG kart · Yerel kütüphane'],
    price: ['Önce bir tanışın', 'İlk 3 yaratık<br><em>bizden.</em>', 'Üç başarılı oluşturma ücretsiz. Sonrasında UFFF Forever ile tek seferlik satın alma yaparak sınırsız yeni yaratık oluştur.', 'Abonelik yok. Eski yaratıkların kilitlenmez.', 'Üç hakkın bittiğinde yeni oluşturma için satın alma gerekir. İptal edilen veya başarısız kayıtlar hak tüketmez. Güncel ücret satın alma ekranında gösterilir.', 'Satın alma soruları'],
    private: ['Sesin, senin iPhone’unda.', 'Kayıtlar cihazında işlenir. UFFF hesabı, reklam veya bulut yapay zekâ yok. Paylaşmak istediğinde kararı sen verirsin.', 'Gizliliği nasıl koruyoruz?'],
    supportTitle: 'Bir yerde<br><em>takıldın mı?</em>', supportDescription: 'UFFF için kayıt, satın alma, paylaşma ve kütüphane desteği. Sık sorulan sorular ve doğrudan e-posta iletişimi.', supportEyebrow: 'UFFF destek',
    supportLead: 'Bazen küçük bir dokunuş yeter. En sık sorulanları burada topladık; gerekirse bize yazabilirsin.',
    contact: ['Birlikte bakalım.', 'Sorunu anlat, kaldığın yerden devam etmene yardımcı olalım.', 'E-posta gönder', 'Mesajına iPhone modelini, iOS sürümünü, gördüğün destek kodunu ve sorunu tekrarlama adımlarını ekle. Ses kaydı veya özel isim göndermen gerekmez.'],
    faqTitle: 'Sık sorulanlar', faqLabel: 'Sorular ve yanıtlar',
    faqs: [
      ['İlk yaratığımı nasıl oluştururum?', 'Önce karakterini, sonra sahneyi ve animasyonu seç. Mikrofon düğmesiyle sesini kaydet. 5–8 saniye önerilir; kayıt en geç 8 saniyede durur ve daha erken durdurabilirsin. Oluşturduktan sonra önizle, ses seçeneğini seç ve kütüphanende sakla.'],
      ['Mikrofon çalışmıyor. Ne yapmalıyım?', 'iPhone’da Ayarlar → Uygulamalar → UFFF bölümünde Mikrofon iznini kontrol et. Sessiz bir ortamda tekrar dene. UFFF yalnızca sen kayıt başlattığında mikrofonu kullanır. Sorun devam ederse uygulamayı kapatıp yeniden aç ve varsa ekrandaki destek koduyla bize yaz.'],
      ['Ses farklı geliyor veya ağız hareketi tam uymuyor.', 'Önizlemede doğal ses seçeneğini dene; ince ve kalın seçenekler sesi bilerek değiştirir. Mikrofonu kapatmadan, telefona normal konuşma mesafesinde, müzik ve arka plan konuşması olmadan kayıt yap. Ağız hareketi kayıttan üretilir ve her hece için kusursuz eşleşme garanti edilmez. Belirgin bir hata varsa saniyesini ve seçtiğin karakter/animasyonu yazman yeterli.'],
      ['Üç ücretsiz hak tam olarak nasıl çalışıyor?', 'Toplam üç başarılı oluşturma ücretsizdir. İptal edilen veya başarısız işlemler hak tüketmez. Üçüncü başarılı oluşturmandan sonra yeni bir yaratık için UFFF Forever satın alman gerekir. Oluşturulmuş yaratıkların kullanılabilir kalır. Bir yaratığı silmek veya yerel içeriği sıfırlamak ücretsiz hakları yenilemez.'],
      ['UFFF Forever abonelik mi?', 'Hayır. UFFF Forever, sınırsız yeni oluşturma sağlayan tek seferlik, tüketilmeyen bir uygulama içi satın almadır. Ücret Apple satın alma ekranında yerel para biriminle gösterilir. İşlemi onaylamadan ücret alınmaz.'],
      ['Satın aldım ama yeni oluşturma kilitli. Nasıl geri yüklerim?', 'Satın alma ekranında “Satın almaları geri yükle” seçeneğini kullan. Satın alırken kullandığın Apple Hesabı ile giriş yaptığından ve internet bağlantın olduğundan emin ol. Apple doğrulamasının tamamlanmasını bekle. Kilit açılmazsa tekrar satın almak yerine bize yaz. Ödeme ve iade işlemlerini Apple yönetir.'],
      ['Videomu veya kartımı nasıl paylaşırım?', 'Bir yaratığı aç ve dışa aktarma seçeneklerinden sesli MP4 video ya da PNG kartı seç. Paylaşım sayfasından hedef uygulamayı seçebilir veya Fotoğraflar’a kaydedebilirsin. PNG bir görseldir; ses ve hareket içermez. İkili sahne, aynı cihazındaki iki yaratığı kullanır.'],
      ['Kütüphanem yedekleniyor mu? Nasıl silerim?', 'Kütüphane bu iPhone’da tutulur ve işletim sistemi yedeğine dahil edilmez. Uygulamayı silmeden veya telefon değiştirmeden önce tutmak istediğin MP4/PNG çıktıları dışa aktar; bu çıktılar düzenlenebilir kütüphane yedeği değildir. Yaratığı veya yalnızca seslerini silebilir, Ayarlar’dan yerel içeriği temizleyebilirsin. Dışarı paylaştığın kopyalar ayrıca silinmelidir.'],
      ['İnternet veya UFFF hesabı gerekiyor mu?', 'Kayıt, oluşturma ve oynatma cihaz üzerinde çalışır; bir UFFF hesabı açman gerekmez. Satın alma, satın almayı geri yükleme ve seçtiğin paylaşım hizmetleri internet gerektirebilir. UFFF bir ses oyuncağıdır; ruh hali, sağlık veya kişilik değerlendirmesi yapmaz.']
    ],
    privacyTitle: 'Sesin sende.<br><em>Kontrol de.</em>', privacyDescription: 'UFFF gizlilik politikası: cihaz üzerinde ses işleme, yerel saklama, satın alma, paylaşım, destek iletişimi ve GitHub Pages.', privacyEyebrow: 'Gizlilik politikası', privacyLead: 'UFFF’te ses kaydı, cihazında küçük bir çizgi filme dönüşür. Bu sayfa uygulamadaki ve bu web sitesindeki veri akışını açıklar.', updated: 'Son güncelleme: 11 Eylül 2026', toc: 'Bu sayfada',
    summary: ['Cihazında işlenir', 'UFFF sunucusuna yüklenmez', 'Paylaşmayı sen seçersin'],
    policy: [
      ['scope', 'Kapsam ve iletişim', `<p>Bu politika, Ali Orkun Ozkul tarafından sunulan UFFF iPhone uygulaması ve UFFF tanıtım/destek web sitesi için geçerlidir. Gizlilik veya kişisel veri talepleri için: ${mail}.</p><p>UFFF bir ses oyuncağıdır; ruh hali, sağlık, kişilik veya demografik özellik değerlendirmesi yapmaz. UFFF hesabı, reklam, uygulama analitiği, bulut yapay zekâ veya uygulamaya ait bir sunucu bulunmaz.</p>`],
      ['recording', 'Ses kaydı ve cihaz üzerinde işleme', '<p>Mikrofon yalnızca sen görünür kayıt işlemini başlattığında kullanılır. Ses analizi, karakter üretimi, ses dönüşümü ve video hazırlama iPhone’unda gerçekleşir. UFFF, kayıtlarını veya yaratıklarını geliştiriciye ya da bir yapay zekâ hizmetine göndermez.</p><p>Ham kayıt, üç işlenmiş ses profili güvenle kaydedildikten sonra silinir. İptal edilen veya başarısız işleme ait geçici kayıtlar da temizlenir. İşlenmiş ses kişiyi tanınabilir kılabilir; ses dönüşümü anonimlik garantisi vermez.</p>'],
      ['storage', 'Yerel saklama ve silme', '<p>Yaratık tarifi, seçtiğin yerel ad, animasyon bilgileri ve işlenmiş sesler, sen silene kadar bu iPhone’da saklanır. Görseli tutarak yalnızca seslerini veya yaratığın tamamını silebilirsin. Ayarlar’dan yerel içeriği ve tercihleri temizlemek de mümkündür.</p><p>Kütüphane işletim sistemi yedeğinden hariç tutulur. Uygulamayı kaldırmak veya telefon değiştirmek içerik kaybına yol açabilir. Önemli video ve kartları önceden dışa aktar. Normal dosya silme uygulanır; fiziksel depolamadan adli olarak geri getirilemez silme garantisi verilmez.</p>'],
      ['permissions', 'İzinler', '<p>Mikrofon izni ses kaydı içindir. Fotoğraflar’a ekleme izni, dışa aktardığın içeriği Fotoğraflar’a kaydetmeyi seçtiğinde kullanılır. İzinlerini iPhone Ayarlar → Uygulamalar → UFFF üzerinden yönetebilirsin. UFFF kişi listeni veya konumunu istemez.</p>'],
      ['sharing', 'Senin seçtiğin paylaşım', '<p>MP4 video veya PNG kartı paylaşmak ve Fotoğraflar’a kaydetmek senin seçiminle başlar. Seçtiğin uygulama, alıcı veya Fotoğraflar/iCloud Fotoğrafları, paylaşılan kopyayı kendi ayarları ve politikalarına göre işleyebilir.</p><p>UFFF içinde bir yaratığı silmek, Fotoğraflar’daki, mesajlardaki veya başka kişilere gönderilmiş kopyaları silmez. Sesli videoların seni veya kaydettiğin başka birini tanınabilir kılabileceğini unutma.</p>'],
      ['purchases', 'Satın alma ve ücretsiz haklar', `<p>Apple, App Store üzerinden ödemeyi ve satın alma geçmişini yönetir. UFFF ödeme kartı bilgilerini almaz. Uygulama, sınırsız oluşturma hakkını açmak veya geri yüklemek için Apple’ın doğrulanmış satın alma durumunu kullanır. Apple’ın veri işleme koşulları için <a href="${applePrivacy}">Apple Gizlilik Politikası</a> geçerlidir.</p><p>Üç ücretsiz başarılı oluşturma sayısı ve yerel satın alma durumu cihaz üzerinde tutulur. İçerikleri silmek kullanılmış ücretsiz hakları yenilemez veya Apple satın almasını iptal etmez.</p>`],
      ['support', 'Destek e-postaları', `<p>Bize e-posta gönderirsen e-posta adresin, mesajın ve kendin eklediğin bilgiler, talebini yanıtlamak ve sorunu çözmek için Ali Orkun Ozkul tarafından işlenir. İletişim iCloud Mail üzerinden yürür; e-posta hizmetinin koşulları da uygulanır. Kayıtlarını veya özel isimlerini göndermen gerekmez.</p><p>Yazışmalar destek talebinin takibi ve geçerli saklama yükümlülükleri için gerektiği sürece tutulur. Destek verilerinle ilgili erişim, düzeltme veya silme talebini ${mail} adresine gönderebilirsin.</p>`],
      ['website', 'Bu web sitesi ve GitHub Pages', `<p>Bu web sitesi GitHub Pages üzerinden sunulur. Site kodunda analitik, reklam, izleme pikseli, çerez, tarayıcıda kalıcı depolama veya harici yazı tipi bulunmaz. Dil seçimi yalnızca başka bir yerel sayfayı açar.</p><p>GitHub Pages’e yapılan ziyaretlerde GitHub, güvenlik amacıyla IP adresini kaydeder; GitHub oturumu açmış olman gerekmez. Barındırma hizmetinin işlediği veriler, saklama ve uluslararası aktarım koşulları için <a href="${githubPages}">GitHub Pages açıklamasını</a> ve <a href="${githubPrivacy}">GitHub Gizlilik Bildirimi’ni</a> inceleyebilirsin. E-posta veya harici bir bağlantıyı açtığında ilgili hizmetin politikası uygulanır.</p>`],
      ['choices', 'Tercihlerin ve taleplerin', `<p>Uygulamanın yerel içeriklerini kendin silebilir, mikrofon ve Fotoğraflar izinlerini kapatabilir, paylaşmamayı seçebilirsin. Geliştirici cihazındaki özel kütüphaneye erişemez. Bize gönderdiğin destek bilgileri için taleplerini ${mail} adresine iletebilirsin.</p><p>Bulunduğun yerdeki yürürlükte olan hukuka göre erişim, düzeltme, silme, işlemeyi kısıtlama, itiraz, veri taşınabilirliği ve bir veri koruma otoritesine şikâyet hakların bulunabilir.</p>`],
      ['updates', 'Değişiklikler', '<p>Uygulamanın veya web sitesinin veri işleme biçimi değişirse bu politika ve üstteki güncelleme tarihi yenilenir. Soruların için destek e-postasından bize ulaşabilirsin.</p>']
    ],
    footer: 'Küçük sesler. Büyük karakterler.', back: 'Başa dön', privacyLink: 'Gizlilik politikası', supportLink: 'Destek', rights: 'Tüm hakları saklıdır.'
  },
  en: {
    name: 'English', skip: 'Skip to content', nav: ['Explore the app', 'Support', 'Privacy'], language: 'Select language',
    title: 'UFFF — Give your voice a starring role.', description: 'Turn your voice into a tiny cartoon. Pick a character, a scene and an animation, then record and share. UFFF for iPhone.',
    eyebrow: 'Little sound. Big character.', heading: 'Let it out.<br>Make it<br><em>UFFF.</em>',
    lead: 'A dramatic sigh, a silly sentence, a tiny birthday wish. Give your voice a starring role in a cartoon of your own.',
    cta: 'See how it works', status: 'Coming soon to the App Store', download: 'View on the App Store', meta: 'iPhone · iOS 18+', free: 'Your first 3 creatures are free',
    art: 'Meet your leading role.', filmAlt: 'UFFF preview showing a yellow Wish Maker character with birthday cakes.', charactersAlt: 'The colourful character selection screen in the UFFF app.',
    how: ['Your stage awaits', 'Four choices.<br>A little extra drama.', 'Character → Scene → Animation → Voice recording. Then preview, smile and share.'],
    steps: [['Pick a character.', 'Choose one of 18 characters to put a face to your voice.'], ['Set the scene.', 'Find a world for your little film among 14 scenes.'], ['Make it move.', 'Give your story a little motion with 18 animations.'], ['Let your voice in.', 'We recommend a 5–8 second recording. Finish it in the preview.']],
    character: ['A little odd. Very you.', 'Every voice<br>has a character.', 'A shy hello, a very long ufff, an unnecessarily dramatic day. Pick your character and let it move to the rhythm of your recording.', ['18 characters', 'Natural, high and low voices', 'Two creatures, one device']],
    occasions: ['No occasion needed', 'But if there’s<br>something to celebrate…', 'Turn an “I love you”, a birthday wish or an ordinary Tuesday into a little performance.', ['Love', 'Valentine’s Day', 'Birthdays', 'Anniversaries', 'Celebrations', 'Just because']],
    share: ['Tiny film. Big smile.', 'Preview. Keep. Send.', 'Export your animation as an MP4 video with sound or a PNG card. Keep your creations in your library and return to them whenever you like.', 'MP4 video · PNG card · Local library'],
    price: ['Get to know each other', 'Your first 3?<br><em>On us.</em>', 'Three successful creations are free. After that, make unlimited new creatures with UFFF Forever, a one-time purchase.', 'No subscription. Your existing creatures stay unlocked.', 'After your three free creations, a purchase is required to create more. Cancelled or failed attempts do not use a credit. The current price appears on the purchase screen.', 'Purchase questions'],
    private: ['Your voice. Your iPhone.', 'Recordings are processed on your device. No UFFF account, ads or cloud AI. You decide when to share.', 'How we handle privacy'],
    supportTitle: 'A little<br><em>stuck?</em>', supportDescription: 'Help with UFFF recording, purchases, sharing and your library. Find answers or get in touch by email.', supportEyebrow: 'UFFF support',
    supportLead: 'Sometimes a small tip is all it takes. Start with the common questions below, or send us a message.',
    contact: ['Let’s figure it out.', 'Tell us what happened so we can help you get back to creating.', 'Send an email', 'Include your iPhone model, iOS version, any support code on screen and steps to reproduce the issue. You do not need to send voice recordings or private names.'],
    faqTitle: 'Common questions', faqLabel: 'Questions and answers',
    faqs: [
      ['How do I make my first creature?', 'Choose a character, then a scene and an animation. Use the microphone button to record your voice. We recommend 5–8 seconds; recording stops at 8 seconds at the latest, and you can stop earlier. Once created, preview your creature, choose a voice option and keep it in your library.'],
      ['The microphone is not working. What should I do?', 'On your iPhone, check microphone permission in Settings → Apps → UFFF. Try again in a quiet place. UFFF only uses the microphone when you start recording. If the issue persists, close and reopen the app, then contact us with any support code shown on screen.'],
      ['My voice sounds different, or the mouth does not quite match.', 'Try the natural voice in the preview; the high and low options intentionally change your voice. Keep the microphone uncovered and speak at a normal distance from your phone without music or background conversation. Mouth movement is generated from your recording; a perfect match for every syllable is not guaranteed. For a noticeable issue, tell us the approximate second and your chosen character and animation.'],
      ['How do the three free creations work?', 'You get three successful creations in total. Cancelled or failed attempts do not use a credit. After your third successful creation, UFFF Forever is required to create a new creature. Existing creatures remain available. Deleting a creature or resetting local content does not renew free credits.'],
      ['Is UFFF Forever a subscription?', 'No. UFFF Forever is a one-time, non-consumable in-app purchase for unlimited new creations. Apple’s purchase screen shows the price in your local currency. You are not charged unless you confirm the transaction.'],
      ['I already purchased, but creating is locked. How do I restore it?', 'Use “Restore purchases” on the purchase screen. Make sure you are signed in with the Apple Account used for the purchase and have an internet connection. Allow Apple’s verification to finish. If it remains locked, contact us before purchasing again. Apple handles payments and refunds.'],
      ['How do I share a video or card?', 'Open a creature and choose an MP4 video with sound or a PNG card from the export options. Use the share sheet to choose a destination app or save to Photos. A PNG is a still image and has no sound or motion. A two-creature scene uses two creatures from the same device.'],
      ['Is my library backed up? How do I delete content?', 'Your library stays on this iPhone and is excluded from the operating system backup. Before uninstalling or changing phones, export any MP4 videos or PNG cards you want to keep; exports are not an editable library backup. You can delete a creature or only its voices, and clear local content in Settings. Copies shared elsewhere must be deleted separately.'],
      ['Do I need internet access or a UFFF account?', 'Recording, creation and playback work on your device without a UFFF account. Purchases, restoring purchases and your chosen sharing services may need internet access. UFFF is a sound toy; it does not assess mood, health or personality.']
    ],
    privacyTitle: 'Your voice.<br><em>Your call.</em>', privacyDescription: 'UFFF privacy policy: on-device voice processing, local storage, purchases, sharing, support email and GitHub Pages.', privacyEyebrow: 'Privacy policy', privacyLead: 'In UFFF, a voice recording becomes a tiny cartoon on your device. This page explains how information is handled in the app and on this website.', updated: 'Last updated: 11 September 2026', toc: 'On this page',
    summary: ['Processed on your device', 'No upload to a UFFF server', 'You choose what to share'],
    policy: [
      ['scope', 'Scope and contact', `<p>This policy covers the UFFF iPhone app and UFFF marketing/support website, provided by Ali Orkun Ozkul. For privacy questions or personal data requests, contact ${mail}.</p><p>UFFF is a sound toy. It does not assess mood, health, personality or demographic characteristics. There is no UFFF account, advertising, app analytics, cloud AI or app backend.</p>`],
      ['recording', 'Recording and on-device processing', '<p>The microphone is used only when you start a visible recording session. Audio analysis, character creation, voice transformation and video rendering happen on your iPhone. UFFF does not send your recordings or creatures to the developer or an AI service.</p><p>The raw recording is deleted after the three processed voice profiles have been safely saved. Temporary recordings from cancelled or failed processing are also cleaned up. A processed voice may still identify a person; voice transformation does not guarantee anonymity.</p>'],
      ['storage', 'Local storage and deletion', '<p>The creature recipe, local name you choose, animation information and processed voices stay on this iPhone until you delete them. You can keep a creature’s appearance while deleting its voices, or delete the whole creature. You can also clear local content and preferences in Settings.</p><p>The library is excluded from the operating system backup. Uninstalling the app or changing phones can result in lost content. Export important videos and cards first. Normal file deletion is used; forensic, irreversible erasure from physical storage is not guaranteed.</p>'],
      ['permissions', 'Permissions', '<p>Microphone permission enables voice recording. Permission to add to Photos is used when you choose to save exported content to Photos. Manage permissions in iPhone Settings → Apps → UFFF. UFFF does not request your contacts or location.</p>'],
      ['sharing', 'Sharing you choose', '<p>Sharing an MP4 video or PNG card, or saving it to Photos, starts with your choice. The destination app, recipient or Photos/iCloud Photos may handle that copy under their own settings and policies.</p><p>Deleting a creature in UFFF does not delete copies in Photos, messages or other people’s devices. Videos with sound can make you or another recorded person identifiable.</p>'],
      ['purchases', 'Purchases and free credits', `<p>Apple manages payment and purchase history through the App Store. UFFF does not receive your payment card details. The app uses verified purchase status from Apple to unlock or restore unlimited creation. See the <a href="${applePrivacy}">Apple Privacy Policy</a> for Apple’s processing practices.</p><p>The count of three free successful creations and local purchase status are held on your device. Deleting content does not renew used free credits or cancel your Apple purchase.</p>`],
      ['support', 'Support emails', `<p>If you email us, Ali Orkun Ozkul processes your email address, message and any information you choose to include to answer your request and resolve the issue. Correspondence uses iCloud Mail, whose service terms also apply. You do not need to send recordings or private names.</p><p>Correspondence is kept for as long as needed to follow up on the request and meet applicable retention obligations. Contact ${mail} to request access to, correction or deletion of support data.</p>`],
      ['website', 'This website and GitHub Pages', `<p>This website is hosted on GitHub Pages. The site code contains no analytics, ads, tracking pixels, cookies, persistent browser storage or external fonts. Changing language simply opens another local page.</p><p>When you visit GitHub Pages, GitHub logs your IP address for security, even if you are not signed in to GitHub. For hosting data, retention and international transfer practices, see the <a href="${githubPages}">GitHub Pages explanation</a> and <a href="${githubPrivacy}">GitHub Privacy Statement</a>. When you open an email or external link, that service’s policy applies.</p>`],
      ['choices', 'Your choices and requests', `<p>You can delete local app content, turn off microphone and Photos permissions, and choose not to share. The developer cannot access your private on-device library. For requests about support information you have sent us, email ${mail}.</p><p>Depending on the law that applies where you live, you may have rights to access, correct, erase, restrict processing, object, portability and a complaint to a data protection authority.</p>`],
      ['updates', 'Updates', '<p>If the app’s or website’s data practices change, this policy and the update date above will be revised. You can contact us at the support email with any questions.</p>']
    ],
    footer: 'Little sounds. Big characters.', back: 'Back to top', privacyLink: 'Privacy policy', supportLink: 'Support', rights: 'All rights reserved.'
  },
  de: {
    name: 'Deutsch', skip: 'Zum Inhalt springen', nav: ['App entdecken', 'Support', 'Datenschutz'], language: 'Sprache wählen',
    title: 'UFFF — Gib deiner Stimme eine Hauptrolle.', description: 'Mach aus deiner Stimme einen kleinen Cartoon. Wähle Figur, Szene und Animation, nimm deine Stimme auf und teile den Moment. UFFF fürs iPhone.',
    eyebrow: 'Kleiner Laut. Großer Charakter.', heading: 'Lass es raus.<br>Mach ein<br><em>UFFF draus.</em>',
    lead: 'Ein tiefer Seufzer, ein alberner Satz, ein kleiner Geburtstagswunsch. Gib deiner Stimme eine Hauptrolle in deinem eigenen kleinen Cartoon.',
    cta: 'So funktioniert’s', status: 'Bald im App Store', download: 'Im App Store ansehen', meta: 'iPhone · iOS 18+', free: 'Die ersten 3 Figuren sind gratis',
    art: 'Deine Hauptrolle wartet.', filmAlt: 'UFFF-Vorschau mit einer gelben Wunschfigur mit Geburtstagstorten.', charactersAlt: 'Die bunte Figurenauswahl in der UFFF-App.',
    how: ['Deine Bühne wartet', 'Vier Entscheidungen.<br>Ein bisschen Drama.', 'Figur → Szene → Animation → Sprachaufnahme. Dann anschauen, schmunzeln und teilen.'],
    steps: [['Figur wählen.', 'Eine von 18 Figuren gibt deiner Stimme ein Gesicht.'], ['Szene aussuchen.', 'Entdecke unter 14 Szenen die Welt für deinen kleinen Film.'], ['Bewegung reinbringen.', 'Mit 18 Animationen kommt Leben in deine Geschichte.'], ['Stimme aufnehmen.', 'Wir empfehlen 5–8 Sekunden. Den Feinschliff gibt’s in der Vorschau.']],
    character: ['Ein bisschen schräg. Ganz du.', 'Jede Stimme<br>hat Charakter.', 'Ein schüchternes Hallo, ein sehr langes Ufff, ein unnötig dramatischer Tag. Wähle deine Figur und lass sie im Rhythmus deiner Aufnahme lebendig werden.', ['18 Figuren', 'Natürliche, hohe und tiefe Stimme', 'Zwei Figuren auf einem Gerät']],
    occasions: ['Geht auch ohne Anlass', 'Und wenn es etwas<br>zu feiern gibt…', 'Mach aus einem „Ich liebe dich“, einem Geburtstagswunsch oder einem ganz normalen Dienstag einen kleinen Auftritt.', ['Liebe', 'Valentinstag', 'Geburtstage', 'Jahrestage', 'Feiern', 'Einfach so']],
    share: ['Kleiner Film. Großes Grinsen.', 'Anschauen. Behalten. Teilen.', 'Exportiere deine Animation als MP4-Video mit Ton oder als PNG-Karte. Deine Werke bleiben in deiner Bibliothek und lassen sich jederzeit wieder öffnen.', 'MP4-Video · PNG-Karte · Lokale Bibliothek'],
    price: ['Lernt euch erst mal kennen', 'Die ersten 3?<br><em>Gehen auf uns.</em>', 'Drei erfolgreiche Erstellungen sind gratis. Danach kannst du mit UFFF Forever durch einen einmaligen Kauf unbegrenzt neue Figuren erstellen.', 'Kein Abo. Vorhandene Figuren bleiben freigeschaltet.', 'Nach drei kostenlosen Erstellungen ist für neue Figuren ein Kauf nötig. Abgebrochene oder fehlgeschlagene Versuche verbrauchen kein Guthaben. Der aktuelle Preis steht im Kaufdialog.', 'Fragen zum Kauf'],
    private: ['Deine Stimme. Dein iPhone.', 'Aufnahmen werden auf deinem Gerät verarbeitet. Kein UFFF-Konto, keine Werbung, keine Cloud-KI. Du entscheidest, wann du etwas teilst.', 'So gehen wir mit Daten um'],
    supportTitle: 'Kommst du<br><em>nicht weiter?</em>', supportDescription: 'Hilfe zu UFFF-Aufnahmen, Käufen, Teilen und Bibliothek. Antworten auf häufige Fragen und Kontakt per E-Mail.', supportEyebrow: 'UFFF Support',
    supportLead: 'Manchmal reicht ein kleiner Tipp. Hier findest du Antworten auf häufige Fragen. Oder schreib uns direkt.',
    contact: ['Schauen wir gemeinsam.', 'Erzähl uns, was passiert ist, damit du bald weitergestalten kannst.', 'E-Mail schreiben', 'Nenne dein iPhone-Modell, die iOS-Version, einen angezeigten Supportcode und die Schritte zum Wiederholen des Problems. Sprachaufnahmen oder private Namen musst du nicht senden.'],
    faqTitle: 'Häufige Fragen', faqLabel: 'Fragen und Antworten',
    faqs: [
      ['Wie erstelle ich meine erste Figur?', 'Wähle zuerst eine Figur, dann eine Szene und eine Animation. Nimm deine Stimme über die Mikrofontaste auf. Wir empfehlen 5–8 Sekunden; spätestens nach 8 Sekunden stoppt die Aufnahme. Du kannst auch früher stoppen. Schau dir die erstellte Figur an, wähle eine Stimmoption und behalte sie in deiner Bibliothek.'],
      ['Das Mikrofon funktioniert nicht. Was kann ich tun?', 'Prüfe auf deinem iPhone unter Einstellungen → Apps → UFFF die Mikrofonberechtigung. Versuche es an einem ruhigen Ort erneut. UFFF nutzt das Mikrofon nur, wenn du eine Aufnahme startest. Schließe und öffne die App bei anhaltenden Problemen erneut und schreib uns gegebenenfalls mit dem angezeigten Supportcode.'],
      ['Die Stimme klingt anders oder der Mund passt nicht ganz.', 'Probiere die natürliche Stimme in der Vorschau. Die hohe und tiefe Variante verändern den Klang absichtlich. Lass das Mikrofon frei und sprich mit normalem Abstand zum Telefon, ohne Musik oder Gespräche im Hintergrund. Die Mundbewegung entsteht aus deiner Aufnahme; eine perfekte Übereinstimmung jeder Silbe wird nicht garantiert. Bei einem deutlichen Fehler reichen die ungefähre Sekunde sowie die gewählte Figur und Animation.'],
      ['Wie funktionieren die drei kostenlosen Erstellungen?', 'Insgesamt sind drei erfolgreiche Erstellungen kostenlos. Abgebrochene oder fehlgeschlagene Versuche verbrauchen kein Guthaben. Nach der dritten erfolgreichen Erstellung brauchst du UFFF Forever für eine neue Figur. Bereits erstellte Figuren bleiben nutzbar. Das Löschen einer Figur oder Zurücksetzen lokaler Inhalte erneuert das kostenlose Guthaben nicht.'],
      ['Ist UFFF Forever ein Abonnement?', 'Nein. UFFF Forever ist ein einmaliger, nicht aufbrauchbarer In-App-Kauf für unbegrenzt viele neue Figuren. Apples Kaufdialog zeigt den Preis in deiner Landeswährung. Eine Zahlung erfolgt erst, wenn du den Kauf bestätigst.'],
      ['Ich habe gekauft, aber neue Figuren sind gesperrt. Wie stelle ich den Kauf wieder her?', 'Wähle im Kaufbildschirm „Käufe wiederherstellen“. Melde dich mit dem beim Kauf verwendeten Apple Account an und stelle eine Internetverbindung her. Warte, bis Apple den Kauf geprüft hat. Bleibt die Funktion gesperrt, schreib uns, bevor du erneut kaufst. Apple verwaltet Zahlungen und Erstattungen.'],
      ['Wie teile ich ein Video oder eine Karte?', 'Öffne eine Figur und wähle beim Export ein MP4-Video mit Ton oder eine PNG-Karte. Über das Teilen-Menü kannst du eine Ziel-App wählen oder in Fotos speichern. Eine PNG-Datei ist ein Standbild ohne Ton und Bewegung. Eine Szene mit zwei Figuren nutzt Figuren auf demselben Gerät.'],
      ['Wird meine Bibliothek gesichert? Wie lösche ich Inhalte?', 'Die Bibliothek bleibt auf diesem iPhone und ist vom Betriebssystem-Backup ausgeschlossen. Exportiere wichtige MP4-Videos und PNG-Karten, bevor du die App löschst oder das Telefon wechselst; Exporte sind kein bearbeitbares Bibliotheks-Backup. Du kannst eine Figur oder nur ihre Stimmen löschen und lokale Inhalte in den Einstellungen entfernen. Bereits geteilte Kopien musst du separat löschen.'],
      ['Brauche ich Internet oder ein UFFF-Konto?', 'Aufnahme, Erstellung und Wiedergabe funktionieren auf deinem Gerät ohne UFFF-Konto. Käufe, das Wiederherstellen von Käufen und ausgewählte Dienste zum Teilen können Internet benötigen. UFFF ist ein Klangspielzeug und beurteilt weder Stimmung noch Gesundheit oder Persönlichkeit.']
    ],
    privacyTitle: 'Deine Stimme.<br><em>Deine Entscheidung.</em>', privacyDescription: 'UFFF-Datenschutzerklärung zu lokaler Sprachverarbeitung, Speicherung, Käufen, Teilen, Support-E-Mails und GitHub Pages.', privacyEyebrow: 'Datenschutzerklärung', privacyLead: 'In UFFF wird deine Sprachaufnahme auf deinem Gerät zu einem kleinen Cartoon. Hier erklären wir, wie die App und diese Website mit Informationen umgehen.', updated: 'Zuletzt aktualisiert: 11. September 2026', toc: 'Auf dieser Seite',
    summary: ['Auf deinem Gerät verarbeitet', 'Kein Upload auf einen UFFF-Server', 'Du entscheidest, was du teilst'],
    policy: [
      ['scope', 'Geltungsbereich und Kontakt', `<p>Diese Erklärung gilt für die iPhone-App UFFF und die UFFF-Produkt- und Supportwebsite von Ali Orkun Ozkul. Bei Datenschutzfragen oder Anfragen zu personenbezogenen Daten: ${mail}.</p><p>UFFF ist ein Klangspielzeug. Es bewertet weder Stimmung, Gesundheit, Persönlichkeit noch demografische Merkmale. Es gibt kein UFFF-Konto, keine Werbung, App-Analytik, Cloud-KI oder ein App-Backend.</p>`],
      ['recording', 'Aufnahme und Verarbeitung auf dem Gerät', '<p>Das Mikrofon wird nur verwendet, wenn du sichtbar eine Aufnahme startest. Audioanalyse, Figurenerstellung, Stimmveränderung und Videoerstellung erfolgen auf deinem iPhone. UFFF sendet deine Aufnahmen oder Figuren weder an den Entwickler noch an einen KI-Dienst.</p><p>Die Rohaufnahme wird gelöscht, sobald die drei verarbeiteten Stimmprofile sicher gespeichert sind. Temporäre Aufnahmen abgebrochener oder fehlgeschlagener Verarbeitung werden ebenfalls entfernt. Auch eine veränderte Stimme kann eine Person erkennbar machen; die Stimmveränderung garantiert keine Anonymität.</p>'],
      ['storage', 'Lokale Speicherung und Löschung', '<p>Das Figurenrezept, der von dir gewählte lokale Name, Animationsinformationen und verarbeitete Stimmen bleiben auf diesem iPhone, bis du sie löschst. Du kannst das Aussehen behalten und nur die Stimmen oder die gesamte Figur löschen. In den Einstellungen kannst du auch lokale Inhalte und Präferenzen entfernen.</p><p>Die Bibliothek ist vom Betriebssystem-Backup ausgeschlossen. Deinstallieren der App oder ein Telefonwechsel kann zum Verlust von Inhalten führen. Exportiere wichtige Videos und Karten vorher. Es erfolgt eine normale Dateilöschung; eine forensisch unwiederbringliche Löschung vom physischen Speicher wird nicht garantiert.</p>'],
      ['permissions', 'Berechtigungen', '<p>Die Mikrofonberechtigung ermöglicht Sprachaufnahmen. Die Berechtigung zum Hinzufügen zu Fotos wird verwendet, wenn du exportierte Inhalte dort speichern möchtest. Verwalte Berechtigungen unter iPhone-Einstellungen → Apps → UFFF. UFFF fordert weder Kontakte noch Standort an.</p>'],
      ['sharing', 'Teilen nach deiner Entscheidung', '<p>Du entscheidest, ob du ein MP4-Video oder eine PNG-Karte teilst oder in Fotos speicherst. Die Ziel-App, Empfänger oder Fotos/iCloud-Fotos können diese Kopie nach ihren eigenen Einstellungen und Richtlinien verarbeiten.</p><p>Das Löschen einer Figur in UFFF entfernt keine Kopien in Fotos, Nachrichten oder auf Geräten anderer Personen. Videos mit Ton können dich oder eine andere aufgenommene Person erkennbar machen.</p>'],
      ['purchases', 'Käufe und kostenloses Guthaben', `<p>Apple verwaltet Zahlung und Kaufverlauf über den App Store. UFFF erhält keine Zahlungskartendaten. Die App verwendet den von Apple bestätigten Kaufstatus, um unbegrenzte Erstellungen freizuschalten oder wiederherzustellen. Für Apples Datenverarbeitung gilt die <a href="${applePrivacy}">Apple-Datenschutzrichtlinie</a>.</p><p>Die Anzahl der drei kostenlosen erfolgreichen Erstellungen und der lokale Kaufstatus werden auf deinem Gerät gespeichert. Das Löschen von Inhalten erneuert kein verbrauchtes Guthaben und storniert keinen Apple-Kauf.</p>`],
      ['support', 'Support-E-Mails', `<p>Wenn du uns eine E-Mail schreibst, verarbeitet Ali Orkun Ozkul deine E-Mail-Adresse, deine Nachricht und freiwillig ergänzte Informationen, um deine Anfrage zu beantworten und das Problem zu lösen. Die Korrespondenz erfolgt über iCloud Mail; dessen Dienstbedingungen gelten ebenfalls. Aufnahmen oder private Namen musst du nicht senden.</p><p>Die Korrespondenz wird so lange aufbewahrt, wie es für die Bearbeitung der Anfrage und geltende Aufbewahrungspflichten erforderlich ist. Anfragen zu Auskunft, Berichtigung oder Löschung von Supportdaten kannst du an ${mail} senden.</p>`],
      ['website', 'Diese Website und GitHub Pages', `<p>Diese Website wird über GitHub Pages bereitgestellt. Ihr Code enthält keine Analytik, Werbung, Trackingpixel, Cookies, dauerhaften Browserspeicher oder externen Schriftarten. Ein Sprachwechsel öffnet lediglich eine andere lokale Seite.</p><p>Beim Besuch von GitHub Pages protokolliert GitHub deine IP-Adresse aus Sicherheitsgründen, auch ohne Anmeldung bei GitHub. Informationen zu Hostingdaten, Aufbewahrung und internationalen Übermittlungen findest du in der <a href="${githubPages}">GitHub-Pages-Erklärung</a> und der <a href="${githubPrivacy}">GitHub-Datenschutzerklärung</a>. Beim Öffnen einer E-Mail oder eines externen Links gilt die Richtlinie des jeweiligen Dienstes.</p>`],
      ['choices', 'Deine Möglichkeiten und Anfragen', `<p>Du kannst lokale App-Inhalte löschen, Mikrofon- und Fotosberechtigungen deaktivieren und auf das Teilen verzichten. Der Entwickler hat keinen Zugriff auf deine private Bibliothek auf dem Gerät. Bei Anfragen zu bereits gesendeten Supportinformationen schreibe an ${mail}.</p><p>Je nach anwendbarem Recht können dir Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Widerspruch, Datenübertragbarkeit sowie Beschwerde bei einer Datenschutzaufsichtsbehörde zustehen.</p>`],
      ['updates', 'Änderungen', '<p>Ändert sich der Umgang der App oder Website mit Daten, werden diese Erklärung und das Aktualisierungsdatum oben angepasst. Bei Fragen erreichst du uns über die Support-E-Mail.</p>']
    ],
    footer: 'Kleine Laute. Große Charaktere.', back: 'Nach oben', privacyLink: 'Datenschutzerklärung', supportLink: 'Support', rights: 'Alle Rechte vorbehalten.'
  }
};

function folder(lang, kind = 'home') {
  return `${lang === 'tr' ? '' : `${lang}/`}${kind === 'home' ? '' : `${kind}/`}`;
}
function relative(from, to) {
  return (path.posix.relative(from || '.', to || '.') || '.') + '/';
}
function render(lang, kind) {
  const t = copy[lang];
  const dir = folder(lang, kind);
  const to = (l, k) => relative(dir, folder(l, k));
  const assets = path.posix.relative(dir || '.', 'assets') + '/';
  const title = kind === 'home' ? t.title : `${kind === 'support' ? t.supportLink : t.privacyLink} — UFFF`;
  const description = kind === 'home' ? t.description : kind === 'support' ? t.supportDescription : t.privacyDescription;
  const nav = ['home', 'support', 'privacy'].map((k, i) => `<a href="${to(lang, k)}"${kind === k ? ' aria-current="page"' : ''}>${t.nav[i]}</a>`).join('');
  const languages = Object.entries(copy).map(([l, x]) => `<a href="${to(l, kind)}" lang="${l}" hreflang="${l}" aria-label="${x.name}"${lang === l ? ' aria-current="true"' : ''}>${l.toUpperCase()}</a>`).join('');
  const img = (type, cls, alt, eager = false) => `<img class="${cls}" src="${assets}${type}-${lang}.png" width="1320" height="2868" alt="${escape(alt)}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
  const icon = `<img src="${assets}app-icon.png" width="1024" height="1024" alt="" class="mascot-tile" decoding="async">`;
  let content;
  if (kind === 'home') {
    content = `<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">${t.eyebrow}</p><h1 id="hero-title">${t.heading}</h1><p class="lead">${t.lead}</p><div class="hero-actions"><a class="button" href="${appStoreAvailable ? appStoreURL : '#how'}">${appStoreAvailable ? t.download : t.cta}<span aria-hidden="true">↗</span></a></div>${appStoreAvailable ? '' : `<p class="availability"><span class="status-dot" aria-hidden="true"></span>${t.status}</p>`}<p class="meta">${t.meta}<br>${t.free}</p></div><div class="hero-art">${icon}${img('film', 'film', t.filmAlt, true)}<span class="art-label" aria-hidden="true">${t.art}</span></div></section>
    <section class="section" id="how"><div class="wrap"><div class="intro-row"><div><p class="eyebrow">${t.how[0]}</p><h2>${t.how[1]}</h2></div><p>${t.how[2]}</p></div><div class="steps">${t.steps.map(([h,p],i)=>`<div class="step"><span class="step-number">0${i+1}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></div></section>
    <section class="section character-section"><div class="wrap split"><div class="character-art">${img('characters','character-screen',t.charactersAlt)}<span class="orbit-word" aria-hidden="true">UFFF!</span></div><div class="feature-copy"><p class="eyebrow">${t.character[0]}</p><h2>${t.character[1]}</h2><p class="lead">${t.character[2]}</p><ul class="feature-list">${t.character[3].map(x=>`<li><span aria-hidden="true">✳</span>${x}</li>`).join('')}</ul></div></div></section>
    <section class="section occasions"><div class="wrap"><p class="eyebrow">${t.occasions[0]}</p><h2>${t.occasions[1]}</h2><p class="lead">${t.occasions[2]}</p><ul class="occasion-list">${t.occasions[3].map((x,i)=>`<li><span aria-hidden="true">${['♡','↗','✳','∞','✦','☺'][i]}</span>${x}</li>`).join('')}</ul><div class="share-note"><span class="share-mark" aria-hidden="true">↗</span><div><p class="eyebrow">${t.share[0]}</p><h3>${t.share[1]}</h3><p>${t.share[2]}</p><span class="meta">${t.share[3]}</span></div></div></div></section>
    <section class="section pricing" id="forever"><div class="wrap pricing-grid"><div><p class="eyebrow">${t.price[0]}</p><h2>${t.price[1]}</h2><p class="lead">${t.price[2]}</p></div><div class="price-detail"><span class="forever-word" aria-hidden="true">3 → ∞</span><h3>${t.price[3]}</h3><p>${t.price[4]}</p><a class="text-link" href="${to(lang,'support')}#faq-4">${t.price[5]} <span aria-hidden="true">↗</span></a></div></div></section>
    <section class="privacy-note wrap"><span class="privacy-mark" aria-hidden="true">✳</span><div><h2>${t.private[0]}</h2><p>${t.private[1]}</p><a class="text-link" href="${to(lang,'privacy')}">${t.private[2]} <span aria-hidden="true">↗</span></a></div></section>`;
  } else if (kind === 'support') {
    content = `<div class="wrap"><section class="page-hero"><p class="eyebrow">${t.supportEyebrow}</p><h1>${t.supportTitle}</h1><p class="lead">${t.supportLead}</p></section><div class="support-layout"><aside class="contact-card"><img src="${assets}app-icon.png" width="1024" height="1024" alt="" loading="lazy"><h2>${t.contact[0]}</h2><p>${t.contact[1]}</p><a class="button" href="mailto:${email}?subject=UFFF%20Support">${t.contact[2]} <span aria-hidden="true">↗</span></a><p class="email-address">${mail}</p><p class="contact-note">${t.contact[3]}</p></aside><section class="faq" aria-label="${t.faqLabel}"><h2>${t.faqTitle}</h2>${t.faqs.map(([q,a],i)=>`<details id="faq-${i+1}"${i===0?' open':''}><summary>${q}<span aria-hidden="true">+</span></summary><div class="answer"><p>${a}</p></div></details>`).join('')}</section></div></div>`;
  } else {
    content = `<div class="wrap"><section class="page-hero privacy-hero"><p class="eyebrow">${t.privacyEyebrow}</p><h1>${t.privacyTitle}</h1><p class="lead">${t.privacyLead}</p><p class="meta updated">${t.updated}</p><ul class="privacy-summary">${t.summary.map(x=>`<li><span aria-hidden="true">↳</span>${x}</li>`).join('')}</ul></section><div class="policy-layout"><nav class="toc" aria-label="${t.toc}"><p>${t.toc}</p><ol>${t.policy.map(([id,h])=>`<li><a href="#${id}">${h}</a></li>`).join('')}</ol></nav><article class="policy">${t.policy.map(([id,h,p],i)=>`<section id="${id}"><span class="policy-number">${String(i+1).padStart(2,'0')}</span><h2>${h}</h2>${p}</section>`).join('')}<a class="text-link" href="#top">${t.back} <span aria-hidden="true">↑</span></a></article></div></div>`;
  }
  return `<!doctype html>
<html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#0e0e16"><meta name="color-scheme" content="dark"><link rel="icon" type="image/png" href="${assets}app-icon.png"><link rel="apple-touch-icon" href="${assets}app-icon.png"><link rel="stylesheet" href="${assets}style.css"></head>
<body class="page-${kind}" id="top"><a class="skip" href="#main">${t.skip}</a><header class="header"><div class="wrap nav"><a class="brand" href="${to(lang,'home')}" aria-label="UFFF"><img src="${assets}app-icon.png" width="44" height="44" alt=""><span class="wordmark" aria-hidden="true">UFFF</span></a><div class="nav-right"><nav class="nav-links" aria-label="${t.nav[0]}">${nav}</nav><nav class="languages" aria-label="${t.language}">${languages}</nav></div></div></header><main id="main">${content}</main><footer class="footer"><div class="wrap"><div class="footer-row"><a class="brand" href="${to(lang,'home')}" aria-label="UFFF"><span class="wordmark" aria-hidden="true">UFFF</span></a><p class="footer-tagline">${t.footer}</p><nav aria-label="UFFF"><a href="${to(lang,'support')}">${t.supportLink}</a><a href="${to(lang,'privacy')}">${t.privacyLink}</a><a href="mailto:${email}">E-mail <span aria-hidden="true">↗</span></a></nav></div><div class="footer-bottom"><small>© 2026 Ali Orkun Ozkul. ${t.rights}</small><a href="https://aozkul.github.io/#projects">${lang==='tr'?'Tüm projeler':lang==='de'?'Alle Projekte':'All projects'} ↗</a><a href="#top">${t.back} ↑</a></div></div></footer></body></html>\n`;
}

for (const lang of Object.keys(copy)) {
  for (const kind of ['home', 'support', 'privacy']) {
    const dir = path.join(publicDir, folder(lang, kind));
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, 'index.html'), render(lang, kind));
  }
}
console.log('Rendered 9 static pages (TR / EN / DE).');
